# netlify.toml

# Configurações de Build
[build]
  # Diretório que contém os arquivos estáticos do site (HTML, CSS, JS, etc.)
  publish = "public"
  
  # Diretório onde as funções serverless (API) estão localizadas
  functions = "api"
  {
    "build": "echo 'Nenhum build necessário. Apenas arquivos estáticos.'"
  },

# Redirecionamento para as funções da API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
